[assembly: System.Reflection.AssemblyDescription("This .NET assembly is part of Nancy.Session.InProc.")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("1.3.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.3.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.3.0.0")]
[assembly: System.Reflection.AssemblyCompany("David Lievrouw")]
[assembly: System.Reflection.AssemblyProduct("Nancy.Session.InProc")]
[assembly: System.CLSCompliant(false)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyDelaySign(false)]
